version: "3.9"

services:
  db:
    image: postgres:15
    container_name: notes_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: notes_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./backend/app:/app/app  # hot reload in dev
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: notes_frontend
    depends_on:
      - backend
    env_file: .env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
